travis:
  secure:
    BINSTAR_TOKEN: FNafcmlRfue38jZUEuK0HRNWka8q5ooXnm2saHy0L8pXNWhcO8dLY4kwoRvBwGCNLB5FrBsGWu22yApQ7kSWmA0vVuMa3I7SdOXkms5NyX4i1jMYbF+/c3r6sugTcQx6H0G0czV8niMLMwOA/0lzYemzsClVg9S+z5RRCXn0NPiS7xPoOsvMea+dAOX+vPKrQpNTDQfFYp0ozGC53ANddLZ7bP9R5wSaWIwHFNZAfOgPuNv2TaUaR4yiw+OanIZUEavvotseFAO9wi4WlnJ6fyC5+mSAV0KNygMydRsydqCps+/IVtmO6zZKv2flAp+arbvoskRc0ASO9I81PqjK1LUsOsd4cWWo33uEK4nvlNvvLRRY3CV71ii6/l65UpwGp0nE3fGHMUxrK4d4/kk+4n85KZXG24JJ+oNNd9xYr2MoqpTKLg8cUbjGMNfXumXTAFhBTW7B66Re5aMEic5d2hnMoSb2lHJgVzmuC21HRjessMoiglP2LaECchPL4Ems+ksNMQtxUdISoCHLtH3bpFZZY2FHEadl9l1EEew9qPRt+pHMOlGtJsIakS/jm3YNEa67IGOV8JiJORQ3cHq+Bxj+ETMsxaYcGzqquPz3s4xTaNVD/WFaQ2Wq58S41LXd4Ps2grcWxUhM6DBd0cidM/MOhK8qN91BVpUIm7RvXIQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
